docs: README change of file path for symbolic linking pre-commit under hooks
mbta/concentrate pull request #220
Opened 2021-11-18 17:53 UTC by uchukwu

README change of file path for symbolic linking pre-commit under hooks

2021-11-18 22:43 UTC, bklebe commented on README.md
> +ln -s ./hooks/pre-commit .git/hooks/pre-commit
```suggestion
ln -s hooks/pre-commit .git/hooks/pre-commit
```

2021-12-02 15:10 UTC, bklebe approved these changes

2021-12-02 15:23 UTC, paulswartz requested changes
@bklebe @uchukwu does doing the link this way run the tests for you? It doesn't on my machine.

2021-12-02 21:45 UTC, bklebe commented
> @bklebe @uchukwu does doing the link this way run the tests for you? It doesn't on my machine.

I should have tested this, it doesn't seem to work. I approved it because it looked right from where the hooks file is, but I assume it's because the symbolic link needs to be relative to the .git folder.

2021-12-06 19:43 UTC, bklebe commented
As an alternative you could use the absolute path to make this instruction less confusing, i.e. `ln -s "$(pwd)/hooks/pre-commit .git/hooks/pre-commit`. Or it looks like you can set `git config core.hooksPath hooks/` from the root of the working tree as well.

2021-12-06 19:57 UTC, bklebe requested changes
requires changes, per @paulswartz

2023-07-21 15:32 UTC, closed without merging