Switch base image to Ubuntu 22.04
mbta/concentrate pull request #263
Opened 2022-12-28 15:58 UTC by nlwstein

#### Summary of changes

**Asana Ticket:** [TICKET_NAME](TICKET_LINK)

[Please include a brief description of what was changed]

2023-01-05 18:26 UTC, bklebe requested changes

2023-01-05 18:26 UTC, bklebe commented on .github/workflows/dev.yml
> +    - cron: '0 5 * * *'
Would you mind moving these cron changes to a separate PR?

2023-01-05 21:24 UTC, nlwstein commented on .github/workflows/dev.yml
> +    - cron: '0 5 * * *'
@bklebe All set! PR - https://github.com/mbta/concentrate/pull/264

2023-01-10 18:57 UTC, bklebe reviewed
looks good Nick — would you mind cleaning up your commit history using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? If you prefer you could also just squash them all into a `chore: update to Erlang 24` commit before you merge in GitHub too.

2023-01-10 18:57 UTC, bklebe commented on .github/workflows/elixir.yml
> +      run: mix compile --force
Sorry I didn't mention this before - could you make an inbound ticket to fix the compiler warnings here and turn `--warnings-as-errors` back on?

2023-01-10 19:49 UTC, nlwstein commented on .github/workflows/elixir.yml
> +      run: mix compile --force
> Sorry I didn't mention this before - could you make an inbound ticket to fix the compiler warnings here and turn `--warnings-as-errors` back on?

@bklebe I can do this, but it will cause the workflow to get marked as failed.

2023-01-10 19:57 UTC, bklebe commented on .github/workflows/elixir.yml
> +      run: mix compile --force
No, I mean you can leave this the way it is, just make a ticket to fix the warnings.

2023-01-10 20:01 UTC, nlwstein commented on .github/workflows/elixir.yml
> +      run: mix compile --force
Sorry - may have misunderstood what you said - do you want the ticket to also be about turning this feature back on? I have created one for that: https://app.asana.com/0/881264583703207/1203676093346059/f

2023-01-10 20:16 UTC, merged