Don't mix predictions
mbta/concentrate pull request #281
Opened 2023-06-05 21:09 UTC by Whoops

#### Summary of changes

**Asana Ticket:** 
[🧠 🐛 Don't mix predictions: Multiple sources to Swiftly, same trip](https://app.asana.com/0/584764604969369/1204277338626227/f)
[🧠 🐛 Don't mix predictions: Multiple buses, same trip](https://app.asana.com/0/584764604969369/1204277338626221/f)

This ensures that we are always using times from the same prediction when merging StopTimeUpdates and filters trips that suggest we'll arrive at a later stop before departing a previous one.

2023-06-08 17:24 UTC, nlwstein requested changes
The only thing that should prob be fixed before merging is the spelling q 😄

2023-06-08 17:24 UTC, nlwstein commented on lib/concentrate/group_filter/time_travel.ex
> +  defp filter_stu(stu, [prev | _] = stus) do
This is really minor but it might be more readable to use `stop_time_update` in place of `stu` (etc) in this file. Not blocking, just an opinion 😄

2023-06-08 17:24 UTC, nlwstein commented on test/concentrate/group_filter/time_travel_test.exs
> +  test "drops predecing stops when prediction involves going back in time" do
nit: did you mean `preceding`?

2023-06-08 17:24 UTC, nlwstein commented on lib/concentrate/group_filter/time_travel.ex
> +      Logger.warning("""
Not blocking - If you use key-value pairs like `trip_id=SOME_VALUE some_other_key=some_other_value ...` in your logs, they will be parsed by Splunk as data. Sometimes it's helpful to append this to the end of your human readable string if you want to filter these error messages quickly.

2023-06-08 20:12 UTC, paulswartz commented on lib/concentrate/stop_time_update.ex
> +      [first, second] = Enum.sort_by([first, second], &Concentrate.StopTimeUpdate.time/1)
question: this is adding quite a few calls to a frequently called codepath: what's the performance like?

2023-06-09 17:19 UTC, Whoops commented on lib/concentrate/group_filter/time_travel.ex
> +  defp filter_stu(stu, [prev | _] = stus) do
Agreed. `stu` was the convention used elsewhere, but it also confused me, so I have changed it to be more verbose.

2023-06-09 17:19 UTC, Whoops commented on test/concentrate/group_filter/time_travel_test.exs
> +  test "drops predecing stops when prediction involves going back in time" do
I did.

2023-06-09 17:20 UTC, Whoops commented on lib/concentrate/group_filter/time_travel.ex
> +      Logger.warning("""
That's useful, I've added `trip_id` and `stop_sequence`

2023-06-09 18:20 UTC, Whoops commented on lib/concentrate/stop_time_update.ex
> +      [first, second] = Enum.sort_by([first, second], &Concentrate.StopTimeUpdate.time/1)
I was hoping to put real world numbers but after profiling Concentrate for 5 minutes I was surprised to find it wasn't called at all! So putting numbers to it a different way...

```elixir
iex(1)> base_stu = %Concentrate.StopTimeUpdate{stop_id: 1} 
...
iex(2)> stus = Enum.map(1..1000000, fn _ -> %{base_stu | arrival_time: :random.uniform(100), departure_time: :random.uniform(100)} end)
...
iex(3): timer.tc(fn -> Enum.reduce(stus, &Concentrate.Mergeable.merge/2) end)

# 3 runs
# Enum.sort_by version
#1: 225,835
#2: 205,168
#3: 259,574

# If statement version
#1: 139,680
#2: 140,282
#3: 140,623
```

After writing it I think the `if` is about as clear as the sort, so I've updated to use that.

2023-06-14 13:53 UTC, nlwstein approved these changes

2023-06-14 13:54 UTC, nlwstein commented
This looks good to me, once the thread w/ @paulswartz is resolved 😄

2023-06-14 14:32 UTC, paulswartz approved these changes

2023-06-15 14:36 UTC, merged