feat: Keolis realtime gtfs
mbta/concentrate pull request #282
Opened 2023-06-09 19:39 UTC by Whoops

#### Summary of changes

**Asana Ticket:** [🚆Keolis Feed Transition](https://app.asana.com/0/584764604969369/1204680576534832/f)

Add the Keolis feed to the configuration. In addition Keolis give us statuses in ALL CAPS, so on_time_statuses needs to be case insensitive.

2023-08-21 19:51 UTC, Whoops commented on config/config.exs
> +    "BOARDING COMPLETE" => "Boarding complete",
These are built off of: https://github.com/mbta/commuter_rail_boarding/blob/main/config/config.exs#L34

"BOARDING COMPLETE" is the only status that does not appear to have an equivalent status in Commuter Rail Boarding.

2023-08-21 21:40 UTC, paulswartz requested changes

2023-08-21 21:40 UTC, paulswartz commented on config/config.exs
> +    gtfs_realtime_enhanced: [
suggestion: this configuration is the default, and other potential users of Concentrate don't have access to these feeds. Instead, they'll go into the configuration in Terraform.

2023-08-21 21:40 UTC, paulswartz commented on lib/concentrate/group_filter/scheduled_stop_times.ex
> +      if String.downcase(status) in @on_time_statuses do
question: what's the performance of this change? It used to be handled with pattern matching, but it doesn't look like that's possible with the implementation here.

2023-08-21 21:40 UTC, paulswartz commented on lib/concentrate/parser/gtfs_realtime_enhanced.ex
> +    Map.get(@boarding_status_override, status, status)
suggestion: since `@boarding_status_override` is available at compile time, this is more efficient to implement with a macro. See https://github.com/mbta/concentrate/blob/master/lib/concentrate/parser/gtfs_realtime_enhanced.ex#L237-L267 later in this file.

2023-08-23 18:08 UTC, Whoops commented on lib/concentrate/group_filter/scheduled_stop_times.ex
> +      if String.downcase(status) in @on_time_statuses do
Just logging the duration, there was not a meaningful change in `group_filter` time with this change. Both with and without the change on my machine the `group_filter` stage took between 22-45ms with most cycles being around 30ms. I haven't charted and graphed them, but just skimming the distribution looks similar. I expect the various ets lookups done in this stage are probably what takes the most time but haven't done any research to very that.

2023-08-23 18:10 UTC, Whoops commented on lib/concentrate/group_filter/scheduled_stop_times.ex
> +      if String.downcase(status) in @on_time_statuses do
Another note: I'm actually OK with dropping this change all together. We discovered that at minimum dotcom is relying on some of these values, which is why. the other part of this PR is converting the status values back to their previous ones. I mainly left the change since the spec treats this as a free-form text field, and felt that being liberal in what we accept was probably best.

2023-08-23 18:21 UTC, Whoops commented on config/config.exs
> +    gtfs_realtime_enhanced: [
Removed

2023-08-23 18:25 UTC, Whoops commented on lib/concentrate/parser/gtfs_realtime_enhanced.ex
> +    Map.get(@boarding_status_override, status, status)
Interesting! Until now I had assumed that doing pattern matching like that would more or less result in the compiler comparing against each string one by one to check for a match and would therefore be essentially linear time. I was going to write a little benchmark to see how that compared to the Map lookup, but it looks like others have already done it and pattern matching wins handily. I'll have to look more into how the compiler is optimizing these, in the meantime this has been updated.

2023-08-23 19:47 UTC, bklebe commented on lib/concentrate/parser/gtfs_realtime_enhanced.ex
> +    Map.get(@boarding_status_override, status, status)
https://www.erlang.org/doc/efficiency_guide/binaryhandling.html is worth reading. Binary pattern matching in Erlang is optimized. 

The implementation of `Map.get/3` pattern matches on a map: https://github.com/elixir-lang/elixir/blob/c521bdb91a77b36be16fdf18d632ad7719de4f91/lib/elixir/lib/map.ex#L526-L537. I assume pattern matching on a map calls the same NIF as `:maps.get/3` does, but I can't figure out where exactly that's implemented because it's in native code.

2023-08-24 16:32 UTC, merged