feat: parsed DIFFERENTIAL feeds coming in from MQTT
mbta/concentrate pull request #304
Opened 2023-09-15 16:18 UTC by paulswartz

#### Summary of changes

**Asana Ticket:** [accept DIFFERENTIAL feeds from Busloc](https://app.asana.com/0/1205365039348894/1205499829140889/f)

[Please include a brief description of what was changed]

2023-09-25 19:20 UTC, nlwstein requested changes
The vast majority of this looks good to me! 

I only had a q regarding the expectation that timestamp will always be float or int. I suspect an accidental string would be more likely than a float value for an epoch timestamp, but it's not a blocking change either.

2023-09-25 19:20 UTC, nlwstein commented on config/config.exs
> +config :logger, level: :info
Is this an intentional change?

2023-09-25 19:20 UTC, nlwstein commented on lib/concentrate/trip_descriptor.ex
> +  def timestamp_truncated(%__MODULE__{timestamp: number}) when is_integer(number) do
Is it worth adding a condition to handle if `number` is valid but cast to a string?

2023-09-25 20:18 UTC, paulswartz commented on config/config.exs
> +config :logger, level: :info
Yep, it's meant to clean up the very aggressive logs from Emqtt: https://github.com/mbta/concentrate/pull/304/commits/431481213f108b1148bab2a6cb8457c92fc7ea96

2023-09-25 20:18 UTC, paulswartz commented on lib/concentrate/trip_descriptor.ex
> +  def timestamp_truncated(%__MODULE__{timestamp: number}) when is_integer(number) do
Good question! At the moment, it's an epoch time, either  integer, or a float (with a number of millisconds/microseconds). Given that only one producer generates floats (Busloc) I don't think it's worth extra complexity. 

If we did want to add the extra complexity, we'd probably add it at the parsing stage, so either way it wouldn't go here.

2023-09-26 22:13 UTC, nlwstein approved these changes

2023-09-27 12:32 UTC, merged