🧠 Implement "uncertainty adapter" within Concentrate
mbta/concentrate pull request #346
Opened 2024-03-21 20:31 UTC by bfauble

#### Summary of changes

**Asana Ticket:** [🧠 Implement "uncertainty adapter" within Concentrate](https://app.asana.com/0/505721188639414/1206586251381038/f)

Update to handle `update_type` field being present at the `TripUpdate` level from `TripUpdates_enhanced.json` feed from RTR. 

`"mid_trip" == 60`
`"at_terminal" == 120`
`"reverse_trip" == 360`

```
%{
  "trip" => %{
    "trip_id" => "trip",
    "route_id" => "route"
  },
  "update_type" => "mid_trip",
  "stop_time_update" => [%{
    "arrival" => %{"time" => 100, "uncertainty" => 60},
    "departure" => %{"time" => 200, "uncertainty" => 60}
  }]
}
```

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206695607194179

2024-03-22 14:09 UTC, paulswartz reviewed
question: is the parser the right place to be making a change to the data? how is this going to work in the future when we want to incorporate other sources of data into these uncertainty updates?

I'm also a little confused about why this particular change is happening in Concentrate, vs RTR. Since RTR is putting in the `update_type` value, why isn't it also updating the `uncertainty` values in the feed it puts out?

2024-03-25 13:49 UTC, bklebe reviewed
@bfauble Thanks for this change! A couple questions:

- I'm a little confused about the implementation plan here. Why are we adding `update_type` to RTR only to convert it back into an opaque uncertainty value in Concentrate?
- Do you think this would be better as a `GroupFilter` than a parser extension? That's what I was imagining, though seeing as the implementation plan here is also different from what I expected, maybe putting it in the parser makes sense.

Let's discuss at standup :)

2024-04-05 18:30 UTC, bklebe approved these changes

2024-04-05 19:53 UTC, bklebe requested changes
As discussed in Slack, this needs updated now that RTR is providing the `update_type` field.

2024-04-05 20:12 UTC, paulswartz reviewed
suggestion: given this rationale for the ticket, I don't think this can live in the parser.
> [...] this would allow [...] for Concentrate to source data from multiple sources to assign and adjust uncertainty values.
> - Will be able to ingest multiple types of inputs to make adjustments to uncertainty in the future - this will only be used to make uncertainty changes based on OIO-indicated sign headway mode initially, but we'll be looking to make more substantial use of this in the future.

If it lives in the parser, there's no way for it to consume multiple sources of data.

2024-04-05 20:22 UTC, paulswartz commented
@bklebe [mentioned](https://github.com/mbta/concentrate/pull/346#pullrequestreview-1957810700) using a `GroupFilter`, which seems like the appropriate place to me as well.

2024-04-09 14:00 UTC, bklebe approved these changes

2024-04-09 15:32 UTC, paulswartz commented
@bfauble I don't see the `update_type` value in the dev Concentrate feed after the deploy.

2024-04-09 15:45 UTC, paulswartz requested changes

2024-04-09 15:45 UTC, paulswartz commented on lib/concentrate/group_filter/uncertainty_value.ex
> +    end)
suggestion: since `calculate_uncertainty` only depends on the `update_type` you shouldn't calculate it within the `map`.

2024-04-09 15:45 UTC, paulswartz commented on lib/concentrate/group_filter/uncertainty_value.ex
> +      StopTimeUpdate.update_uncertainty(stu, calculate_uncertainty(update_type))
question: this looks like it always sets the `uncertainty` even if `update_type` isn't set. won't this override the uncertainty we get from non-RTR sources?

2024-04-09 15:45 UTC, paulswartz commented on lib/concentrate/trip_descriptor.ex
> +          update_type: merge_update_type(first.update_type, second.update_type)
suggestion: `first.update_type || second.update_type`

2024-04-09 15:45 UTC, paulswartz commented on test/concentrate/group_filter/unceratinty_value_test.exs
> +    test "populates uncertainty in TripDescriptor based on update_type value of other" do
suggestion: can you add a test than an `uncertainty` value without an `update_type` is kept?

2024-04-09 15:45 UTC, paulswartz commented on config/config.exs
> +    Concentrate.GropuFilter.UncertaintyValue
suggestion: typo, should be `Concentrate.GroupFilter.UncertaintyValue`

2024-04-09 15:45 UTC, paulswartz commented on lib/concentrate/encoder/gtfs_realtime_helpers.ex
> +                update_type: update_type
question: do you need the changes to this file? This are generic to both enhanced and non-enhanced feeds, and the non-enhanced feeds don't have an `update_type`.

2024-04-25 13:06 UTC, paulswartz reviewed
Definitely looks like there's a performance drop with this: 
![Screenshot 2024-04-25 at 9 03 41 AM](https://github.com/mbta/concentrate/assets/214921/a61d9cc5-18a3-4bcb-9fd0-badf3e4e51cd)
Let me know if you need help looking into it!

2024-04-26 14:10 UTC, paulswartz approved these changes
Performance looks better now!

2024-04-26 17:02 UTC, merged